name: Run Ansible playbook
description: Execute Ansible playbook on selected hosts
branding:
  color: red
  icon: play
inputs:
  playbook:
    description: Ansible playbook filepath
    required: true
  requirements:
    description: Ansible Galaxy requirements filepath
    required: false
  directory:
    description: Root directory of Ansible project (defaults to current)
    required: false
  configuration:
    description: Ansible configuration file content (ansible.cfg)
    required: false
  key:
    description: SSH private key used to connect to the host
    required: false
  inventory:
    description: Custom content to write into hosts
    required: false
  vault_password:
    description: The password used for decrypting vaulted files
    required: false
  known_hosts:
    description: Contents of SSH known_hosts file
    required: false
  options:
    description: Extra options that should be passed to ansible-playbook command
    required: false
  sudo:
    description: Set to "true" if root is required for running your playbook
    required: false
    default: "false"
  no_color:
    description: Set to "true" if the Ansible output should not include colors (defaults to "false")
    required: false
    default: "false"
  check_mode:
    description: Set to "true" to enable check (dry-run) mode
    required: false
    default: "false"
outputs:
  output:
    description: The captured output of both stdout and stderr from the Ansible Playbook run
runs:
  using: node20
  main: main.js
  post: post.js
