name: Run Ansible playbook
description: Execute Ansible playbook on selected hosts
branding:
  color: red
  icon: play
inputs:
  playbook:
    description: Ansible playbook filepath
    required: true
  requirements:
    description: Ansible Galaxy requirements filepath
    required: false
  directory:
    description: Root directory of Ansible project (defaults to current)
    required: false
  key:
    description: SSH private key used to connect to the host
    required: false
  inventory:
    description: Custom content to write into hosts
    required: false
  vault_password:
    description: The password used for decrypting vaulted files
    required: false
  known_hosts:
    description: Contents of SSH known_hosts file
    required: false
  options:
    description: Extra options that should be passed to ansible-playbook command
    required: false
  sudo:
    description: Set to "true" if root is required for running your playbook
    required: false
outputs:
  stdout:
    description: The captured output of stdout from the Ansible Playbook run
  stderr:
    description: The captured output of stderr from the Ansible Playbook run
runs:
  using: node12
  main: main.js
  post: post.js
